"""

Revision ID: e35de249f203
Revises: 
Create Date: 2024-05-26 20:48:17.831742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35de249f203'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('sport', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('league', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.DATE(), nullable=True),
    sa.Column('event_time', sa.String(length=255), nullable=True),
    sa.Column('home_team', sa.String(length=255), nullable=True),
    sa.Column('away_team', sa.String(length=255), nullable=True),
    sa.Column('home_odds', sa.String(length=255), nullable=True),
    sa.Column('away_odds', sa.String(length=255), nullable=True),
    sa.Column('draw_odds', sa.String(length=255), nullable=True),
    sa.Column('extracted_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('extraction_id'),
    schema='raw'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_data', schema='raw')
    # ### end Alembic commands ###
